all: 
	pyuic4 SearchWidget.ui -o Ui_SearchWidget.py -x
	pyuic4 Table.ui -o Ui_Table.py -x
	pyuic4 Image.ui -o Ui_Image.py -x
	pyuic4 Link.ui -o Ui_Link.py -x
	pyuic4 StyleDialog.ui -o Ui_StyleDialog.py -x
