# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Image.ui'
#
# Created: Wed Feb 02 23:12:15 2011
#      by: PyQt5 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

class Ui_Image(object):
    def setupUi(self, Image):
        Image.setObjectName("Image")
        Image.resize(418, 331)
        Image.setModal(True)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Image)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(Image)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.uri = QtGui.QLineEdit(Image)
        self.uri.setEnabled(True)
        self.uri.setObjectName("uri")
        self.horizontalLayout.addWidget(self.uri)
        self.brower = QtGui.QToolButton(Image)
        self.brower.setObjectName("brower")
        self.horizontalLayout.addWidget(self.brower)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(Image)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.alt = QtGui.QLineEdit(Image)
        self.alt.setObjectName("alt")
        self.horizontalLayout_2.addWidget(self.alt)
        spacerItem = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.preview = QtWebKit.QWebView(Image)
        self.preview.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.preview.setUrl(QtCore.QUrl("about:blank"))
        self.preview.setObjectName("preview")
        self.horizontalLayout_9.addWidget(self.preview)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(Image)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.width = QtGui.QSpinBox(Image)
        self.width.setMaximum(999999)
        self.width.setObjectName("width")
        self.horizontalLayout_3.addWidget(self.width)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(Image)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.height = QtGui.QSpinBox(Image)
        self.height.setMaximum(999999)
        self.height.setObjectName("height")
        self.horizontalLayout_4.addWidget(self.height)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(Image)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.border = QtGui.QSpinBox(Image)
        self.border.setMaximum(20)
        self.border.setObjectName("border")
        self.horizontalLayout_5.addWidget(self.border)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtGui.QLabel(Image)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.hspace = QtGui.QSpinBox(Image)
        self.hspace.setObjectName("hspace")
        self.horizontalLayout_6.addWidget(self.hspace)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtGui.QLabel(Image)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.vspace = QtGui.QSpinBox(Image)
        self.vspace.setObjectName("vspace")
        self.horizontalLayout_7.addWidget(self.vspace)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtGui.QLabel(Image)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.alignment = QtGui.QComboBox(Image)
        self.alignment.setObjectName("alignment")
        self.alignment.addItem("")
        self.alignment.addItem("")
        self.alignment.addItem("")
        self.alignment.addItem("")
        self.horizontalLayout_8.addWidget(self.alignment)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btn = QtGui.QDialogButtonBox(Image)
        self.btn.setOrientation(QtCore.Qt.Horizontal)
        self.btn.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.btn.setObjectName("btn")
        self.verticalLayout.addWidget(self.btn)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Image)
        QtCore.QObject.connect(self.btn, QtCore.SIGNAL("accepted()"), Image.accept)
        QtCore.QObject.connect(self.btn, QtCore.SIGNAL("rejected()"), Image.reject)
        QtCore.QMetaObject.connectSlotsByName(Image)

    def retranslateUi(self, Image):
        Image.setWindowTitle(QtGui.QApplication.translate("Image", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Image", "URI", None, QtGui.QApplication.UnicodeUTF8))
        self.brower.setText(QtGui.QApplication.translate("Image", "brower...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Image", "Alt Text", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Image", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Image", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Image", "Border", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Image", "HSpace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Image", "VSpace", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Image", "Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.alignment.setItemText(0, QtGui.QApplication.translate("Image", "<not set>", None, QtGui.QApplication.UnicodeUTF8))
        self.alignment.setItemText(1, QtGui.QApplication.translate("Image", "left", None, QtGui.QApplication.UnicodeUTF8))
        self.alignment.setItemText(2, QtGui.QApplication.translate("Image", "right", None, QtGui.QApplication.UnicodeUTF8))
        self.alignment.setItemText(3, QtGui.QApplication.translate("Image", "center", None, QtGui.QApplication.UnicodeUTF8))

from PyQt5 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Image = QtGui.QDialog()
    ui = Ui_Image()
    ui.setupUi(Image)
    Image.show()
    sys.exit(app.exec_())

