# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Table.ui'
#
# Created: Wed Feb 02 23:12:15 2011
#      by: PyQt5 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

class Ui_Table(object):
    def setupUi(self, Table):
        Table.setObjectName("Table")
        Table.resize(433, 275)
        Table.setAutoFillBackground(True)
        Table.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(Table)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rows = QtGui.QSpinBox(Table)
        self.rows.setMinimumSize(QtCore.QSize(50, 0))
        self.rows.setProperty("value", 3)
        self.rows.setObjectName("rows")
        self.gridLayout.addWidget(self.rows, 2, 1, 1, 1)
        self.columns = QtGui.QSpinBox(Table)
        self.columns.setProperty("value", 2)
        self.columns.setObjectName("columns")
        self.gridLayout.addWidget(self.columns, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 7, 1, 1)
        self.widthtype = QtGui.QComboBox(Table)
        self.widthtype.setObjectName("widthtype")
        self.widthtype.addItem("")
        self.widthtype.addItem("")
        self.gridLayout.addWidget(self.widthtype, 2, 6, 1, 1)
        self.label_5 = QtGui.QLabel(Table)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.width = QtGui.QSpinBox(Table)
        self.width.setMinimumSize(QtCore.QSize(75, 0))
        self.width.setMaximumSize(QtCore.QSize(75, 16777215))
        self.width.setMinimum(1)
        self.width.setMaximum(2000)
        self.width.setProperty("value", 500)
        self.width.setObjectName("width")
        self.gridLayout.addWidget(self.width, 2, 4, 1, 1)
        self.height = QtGui.QSpinBox(Table)
        self.height.setMinimumSize(QtCore.QSize(75, 0))
        self.height.setMaximumSize(QtCore.QSize(75, 16777215))
        self.height.setObjectName("height")
        self.gridLayout.addWidget(self.height, 4, 4, 1, 1)
        self.label = QtGui.QLabel(Table)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(Table)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Table)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.label_4 = QtGui.QLabel(Table)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_9 = QtGui.QLabel(Table)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.line = QtGui.QFrame(Table)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtGui.QLabel(Table)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.id = QtGui.QLineEdit(Table)
        self.id.setObjectName("id")
        self.gridLayout_2.addWidget(self.id, 1, 1, 1, 1)
        self.style_2 = QtGui.QLabel(Table)
        self.style_2.setObjectName("style_2")
        self.gridLayout_2.addWidget(self.style_2, 2, 0, 1, 1)
        self.style = QtGui.QLineEdit(Table)
        self.style.setObjectName("style")
        self.gridLayout_2.addWidget(self.style, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ldflsjf = QtGui.QLabel(Table)
        self.ldflsjf.setObjectName("ldflsjf")
        self.horizontalLayout.addWidget(self.ldflsjf)
        self.border = QtGui.QSpinBox(Table)
        self.border.setMaximum(20)
        self.border.setProperty("value", 1)
        self.border.setObjectName("border")
        self.horizontalLayout.addWidget(self.border)
        self.label_7 = QtGui.QLabel(Table)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.cellspacing = QtGui.QSpinBox(Table)
        self.cellspacing.setProperty("value", 1)
        self.cellspacing.setObjectName("cellspacing")
        self.horizontalLayout.addWidget(self.cellspacing)
        self.label_8 = QtGui.QLabel(Table)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.cellpadding = QtGui.QSpinBox(Table)
        self.cellpadding.setProperty("value", 1)
        self.cellpadding.setObjectName("cellpadding")
        self.horizontalLayout.addWidget(self.cellpadding)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.btn = QtGui.QDialogButtonBox(Table)
        self.btn.setOrientation(QtCore.Qt.Horizontal)
        self.btn.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.btn.setObjectName("btn")
        self.verticalLayout.addWidget(self.btn)

        self.retranslateUi(Table)
        QtCore.QObject.connect(self.btn, QtCore.SIGNAL("accepted()"), Table.accept)
        QtCore.QObject.connect(self.btn, QtCore.SIGNAL("rejected()"), Table.reject)
        QtCore.QMetaObject.connectSlotsByName(Table)

    def retranslateUi(self, Table):
        Table.setWindowTitle(QtGui.QApplication.translate("Table", "Table", None, QtGui.QApplication.UnicodeUTF8))
        self.widthtype.setItemText(0, QtGui.QApplication.translate("Table", "pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.widthtype.setItemText(1, QtGui.QApplication.translate("Table", "percent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Table", "pixels", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Table", "Rows", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Table", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Table", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Table", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Table", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Advanced</span>(leave blank if donot know what\'s this)</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Table", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.style_2.setText(QtGui.QApplication.translate("Table", "Style", None, QtGui.QApplication.UnicodeUTF8))
        self.ldflsjf.setText(QtGui.QApplication.translate("Table", "Border", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Table", "Cell spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Table", "Cell padding", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Table = QtGui.QDialog()
    ui = Ui_Table()
    ui.setupUi(Table)
    Table.show()
    sys.exit(app.exec_())

