all: 
	pyuic4 YeahdocList.ui -o Ui_YeahdocList.py -x
	pyuic4 YeahdocEditor.ui -o Ui_YeahdocEditor.py -x
	pyuic4 NewYeahdocCategory.ui -o Ui_NewYeahdocCategory.py -x
	pyuic4 YeahdocPage.ui -o Ui_YeahdocPage.py -x
	